//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundOps.QuickBooksWF.Tests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.GetHere")]
    public interface GetHere {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="GetHere")]
        void GetHere();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface GetHereChannel : FoundOps.QuickBooksWF.Tests.ServiceReference1.GetHere, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetHereClient : System.ServiceModel.ClientBase<FoundOps.QuickBooksWF.Tests.ServiceReference1.GetHere>, FoundOps.QuickBooksWF.Tests.ServiceReference1.GetHere {
        
        public GetHereClient() {
        }
        
        public GetHereClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GetHereClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetHereClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GetHereClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void GetHere() {
            base.Channel.GetHere();
        }
    }
}
