//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.488
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoundOps.QuickBooksWF.Tests.UpdateDelete {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UpdateDelete.UpdateDelete")]
    public interface UpdateDelete {
        
        // CODEGEN: Generating message contract since the operation Start is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/UpdateDelete/Start")]
        void Start(FoundOps.QuickBooksWF.Tests.UpdateDelete.Start request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class Start {
        
        public Start() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UpdateDeleteChannel : FoundOps.QuickBooksWF.Tests.UpdateDelete.UpdateDelete, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UpdateDeleteClient : System.ServiceModel.ClientBase<FoundOps.QuickBooksWF.Tests.UpdateDelete.UpdateDelete>, FoundOps.QuickBooksWF.Tests.UpdateDelete.UpdateDelete {
        
        public UpdateDeleteClient() {
        }
        
        public UpdateDeleteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UpdateDeleteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateDeleteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UpdateDeleteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void FoundOps.QuickBooksWF.Tests.UpdateDelete.UpdateDelete.Start(FoundOps.QuickBooksWF.Tests.UpdateDelete.Start request) {
            base.Channel.Start(request);
        }
        
        public void Start() {
            FoundOps.QuickBooksWF.Tests.UpdateDelete.Start inValue = new FoundOps.QuickBooksWF.Tests.UpdateDelete.Start();
            ((FoundOps.QuickBooksWF.Tests.UpdateDelete.UpdateDelete)(this)).Start(inValue);
        }
    }
}
